-- CRIA UM USUARIO
CREATE USER NOME_USUARIO IDENTIFIED BY "SENHA_USUARIO";
-- CONCEDE PRIVILEGIOS AO USUARIO CRIADO
GRANT ALL PRIVILEGES TO NOME_USUARIO;
-- DELETA UM USUARIO
DROP USER NOME_USUARIO;

-- DESING E CRIACAO DE UM BANCO DE DADOS
-- CRIA UMA TABELA EXEMPLO
CREATE TABLE EXEMPLO(
    ID_USER INT, 
    NOME_USER VARCHAR2(50),
    IDADE_USER INT
);

-- INSERE DADOS EM UMA TABELA
INSERT INTO EXEMPLO(ID_USER, NOME_USER, IDADE_USER) VALUES
    (1, "Joao", 18),
    (2, "Maria", 18);

-- SELECIONA DADOS DE UMA TABELA
SELECT * FROM EXEMPLO;
SELECT NOME_USER, IDADE_USER FROM EXEMPLO;

-- ORDENA DADOS DE UMA TABELA
SELECT * FROM EXEMPLO
ORDER BY ID_USER;

-- FILTRA DADOS DE UMA TABELA
SELECT * FROM EXEMPLO
WHERE IDADE_USER >= 18;

-- ALTERA DADOS DAS TABELAS
UPDATE EXEMPLOS
SET NOME_USER = "FULANO"
WHERE ID_USER = 1;

-- DELETA DADOS DE UMA TABELA
DELETE FROM EXEMPLO
WHERE ID_USER = 2;

-- EXCLUI TODOS OS DADOS DE UMA TABELA
TRUNCATE TABLE EXEMPLO;

CREATE TABLE TESTE(
    CPF VARCHAR2(100) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CARTAO INT NOT NULL,
    TELEFONE VARCHAR2(100) NOT NULL,
    PRIMARY KEY(CPF)
);
