CREATE TABLE LIVROS(
    ID_LIVRO INT,
    NOME_LIVRO VARCHAR2(60),
    ANO_LIVRO CHAR(4),
    AUTOR VARCHAR2(50),
    EDITORA VARCHAR2(50),
    ISBN_LIVRO VARCHAR2(20),
    EDICAO VARCHAR(50)
);

INSERT INTO LIVROS(ID_LIVRO, NOME_LIVRO, ANO_LIVRO, AUTOR, EDITORA, ISBN_LIVRO, EDICAO) VALUES
    (1, 'COMO MOVER O MONTE FUJI', '2005', 'Ibraima Dafonte Tavares', 'Ediouro', '9788500016394', '1 EDICAO');
    
/* ATUALIZA DADOS: - NOME DO LIVRO
    UPDATE LIVROS
    SET NOME_LIVRO = 'Como Mover o Monte Fuji?'
        WHERE ID_LIVRO = 1; */

INSERT INTO LIVROS(ID_LIVRO, NOME_LIVRO, ANO_LIVRO, AUTOR, EDITORA, ISBN_LIVRO, EDICAO) VALUES
    (2, 'Harry Potter e a Pedra Filosofal - Capa Dura', '2017', 'J. K. Rowling', 'Rocco', '8532530788', '1 EDICAO');
INSERT INTO LIVROS(ID_LIVRO, NOME_LIVRO, ANO_LIVRO, AUTOR, EDITORA, ISBN_LIVRO, EDICAO) VALUES
    (3, 'Harry Potter e a Camara Secreta - Capa Dura', '2017', 'J. K. Rowling', 'Rocco', '8532530796', '1 EDICAO');
INSERT INTO LIVROS(ID_LIVRO, NOME_LIVRO, ANO_LIVRO, AUTOR, EDITORA, ISBN_LIVRO, EDICAO) VALUES
    (4, 'Harry Potter e o Prisioneiro de Azkaban - Capa Dura', '2017', 'J. K. Rowling', 'Rocco', '853253080X', '1 EDICAO');
INSERT INTO LIVROS(ID_LIVRO, NOME_LIVRO, ANO_LIVRO, AUTOR, EDITORA, ISBN_LIVRO, EDICAO) VALUES
    (5, 'Harry Potter e o Calice de Fogo - Capa Dura', '2020', 'J. K. Rowling', 'Rocco', '8532531792', '1 EDICAO');
INSERT INTO LIVROS(ID_LIVRO, NOME_LIVRO, ANO_LIVRO, AUTOR, EDITORA, ISBN_LIVRO, EDICAO) VALUES
    (6, 'Harry Potter e a Ordem da Fenix - Capa Dura', '2020', 'J. K. Rowling', 'Rocco', '8532531806', '1 EDICAO');
INSERT INTO LIVROS(ID_LIVRO, NOME_LIVRO, ANO_LIVRO, AUTOR, EDITORA, ISBN_LIVRO, EDICAO) VALUES
    (7, 'Harry Potter e o Enigma do Principe - Capa Dura', '2017', 'J. K. Rowling', 'Rocco', '8532530834', '1 EDICAO');
INSERT INTO LIVROS(ID_LIVRO, NOME_LIVRO, ANO_LIVRO, AUTOR, EDITORA, ISBN_LIVRO, EDICAO) VALUES
    (8, 'Harry Potter e as Reliquias da Morte - Capa Dura', '2017', 'J. K. Rowling', 'Rocco', '8532530842', '1 EDICAO');

/* ATUALIZA AUTOR
UPDATE LIVROS
SET AUTOR = 'William Poundstone'
    WHERE ID_LIVRO = 1; */
