CREATE TABLE CLIENTES(
    ID_CLIENTE INT,
    NOME_CLIENTE VARCHAR2(50),
    SEXO VARCHAR2(1),
    EMAIL VARCHAR2(50),
    DATA_NASCIMENTO DATE
);
CREATE TABLE PRODUTOS(
    ID_PRODUTO INT,
    NOME_PRODUTO VARCHAR2(50),
    MARCA VARCHAR2(50),
    CATEGORIA VARCHAR2(50),
    PRECO_UNIT NUMBER (10, 2),
    CUSTO_UNIT NUMBER (10, 2)
);
CREATE TABLE VENDAS(
    ID_VENDA INT,
    DATA_VENDA DATE,
    ID_CLIENTE INT,
    ID_PRODUTO INT,
    QUANTIDADE NUMBER(10, 2)
);
INSERT INTO CLIENTES(ID_CLIENTE, NOME_CLIENTE, SEXO, EMAIL, DATA_NASCIMENTO) VALUES
    (1, 'Joao', 'M', 'joao@gmail.com', '12/10/2000');
INSERT INTO CLIENTES(ID_CLIENTE, NOME_CLIENTE, SEXO, EMAIL, DATA_NASCIMENTO) VALUES
    (2, 'Maria', 'F', 'maria@gmail.com', '25/06/1999');
INSERT INTO CLIENTES(ID_CLIENTE, NOME_CLIENTE, SEXO, EMAIL, DATA_NASCIMENTO) VALUES
    (3, 'Bianca', 'F', 'bianca@gmail.com', '01/09/2005');
    
INSERT INTO PRODUTOS(ID_PRODUTO, NOME_PRODUTO, MARCA, CATEGORIA, PRECO_UNIT, CUSTO_UNIT) VALUES
    (1, 'Xbox Series X', 'Microsoft', 'Console', 4200, 3500);
INSERT INTO PRODUTOS(ID_PRODUTO, NOME_PRODUTO, MARCA, CATEGORIA, PRECO_UNIT, CUSTO_UNIT) VALUES
    (2, 'Xbox Series S', 'Microsoft', 'Console', 2800, 2100);
INSERT INTO PRODUTOS(ID_PRODUTO, NOME_PRODUTO, MARCA, CATEGORIA, PRECO_UNIT, CUSTO_UNIT) VALUES
    (3, 'Volante G29', 'Logitech', 'Hardware', 2200, 1500);
    
INSERT INTO VENDAS (ID_VENDA, DATA_VENDA, ID_CLIENTE, ID_PRODUTO, QUANTIDADE) VALUES
    (1, '25/04/2023', 1, 1, 1);    
INSERT INTO VENDAS (ID_VENDA, DATA_VENDA, ID_CLIENTE, ID_PRODUTO, QUANTIDADE) VALUES
    (2, '26/04/2023', 3, 2, 1);
INSERT INTO VENDAS (ID_VENDA, DATA_VENDA, ID_CLIENTE, ID_PRODUTO, QUANTIDADE) VALUES
    (3, '12/05/2023', 2, 3, 1);
    
SELECT * FROM CLIENTES;
SELECT * FROM PRODUTOS;
SELECT * FROM VENDAS;

SELECT
    VENDAS.ID_VENDA,
    VENDAS.DATA_VENDA AS "DATA",
    CLIENTES.NOME_CLIENTE AS "CLIENTE",
    PRODUTOS.NOME_PRODUTO AS "PRODUTO COMPRADO",
    PRODUTOS.MARCA
FROM VENDAS
INNER JOIN CLIENTES
    ON VENDAS.ID_CLIENTE = CLIENTES.ID_CLIENTE
INNER JOIN PRODUTOS
    ON VENDAS.ID_PRODUTO = PRODUTOS.ID_PRODUTO
ORDER BY VENDAS.DATA_VENDA;
